Repository andela/ah-rambo-backend, pull requests merged in 2019-08, with the labels that each got.

#15 #167573194 Build Out User Signup Feature
  .env.sample
  package-lock.json
  package.json
  server/controllers/Users.js
  server/database/migrations/20190730111558-create-user.js
  server/database/models/index.js
  server/database/models/user.js
  server/database/seeds/20190730180408-my-seed-file.js
  server/docs/authors-haven-api.yml
  server/helpers/checkExistingUser.js
  server/helpers/index.js
  server/helpers/serverResponse.js
  server/index.js
  server/routes/index.js
  server/routes/user.js
  test/index.test.js
  test/users/_mocks_/index.js
  test/users/index.js
  test/users/signup.test.js
Labels: pr:review, type:feature

#19 #167190529 Validate User Signup Inputs
  .gitignore
  package-lock.json
  package.json
  server/helpers/index.js
  server/helpers/validationHelper.js
  server/middlewares/userValidation.js
  server/schemas/userSignup.js
  test/index.test.js
  test/middlewares/userValidation.test.js
Labels: pr:ready, type:feature

#18 #167619168 Create Sessions Table
  server/database/migrations/20190731135151-create-session.js
  server/database/models/index.js
  server/database/models/session.js
  server/database/seeds/20190731140725-demo-session.js
  test/helpers/index.test.js
  test/helpers/sessionMigration.test.js
  test/index.test.js
Labels: pr:review, priority:high, type:chore

#21 Fix Bugs with Sign Up Schema
  package.json
  server/controllers/Users.js
  server/helpers/validationHelper.js
  server/routes/user.js
  server/schemas/userSignup.js
  test/middlewares/userValidation.test.js
  test/users/_mocks_/index.js
  test/users/signup.test.js
Labels: pr:review, priority:high, type:fix

#13 #167190527 JWT Authentication
  .env.sample
  package-lock.json
  package.json
  server/database/seeds/20190731140725-demo-session.js
  server/helpers/checkExistingUser.js
  server/helpers/findToken.js
  server/helpers/generateToken.js
  server/helpers/index.js
  server/middlewares/index.js
  server/middlewares/verifyToken.js
  test/helpers/__mocks__/index.js
  test/helpers/findToken.test.js
  test/helpers/generateToken.test.js
  test/helpers/index.js
  test/helpers/sessionMigration.test.js
  test/index.test.js
  test/middlewares/index.js
  test/middlewares/verifyToken.test.js
Labels: pr:ready, type:feature

#14 #167573212 Implement Login Feature
  package-lock.json
  package.json
  server/controllers/Sessions.js
  server/controllers/Users.js
  server/database/models/session.js
  server/database/seeds/20190730180408-my-seed-file.js
  server/database/seeds/20190731140725-demo-session.js
  server/docs/authors-haven-api.yml
  server/helpers/dateHelper.js
  server/helpers/findToken.js
  server/helpers/findUser.js
  server/helpers/getUserAgent.js
  server/helpers/index.js
  server/middlewares/verifyToken.js
  server/routes/index.js
  server/routes/session.js
  test/helpers/__mocks__/index.js
  test/helpers/dateHelper.test.js
  test/helpers/findToken.test.js
  test/helpers/generateToken.test.js
  test/helpers/index.js
  test/helpers/index.test.js
  test/helpers/sessionMigration.test.js
  test/middlewares/verifyToken.test.js
  test/users/__mocks__/index.js
  test/users/__mocks__/user.js
  test/users/index.js
  test/users/sessions.test.js
  test/users/signup.test.js
Labels: pr:ready, priority:high, priority:immediate, type:feature

#17 #167574878 Facebook Social Login
  .env.sample
  package-lock.json
  package.json
  server/controllers/Auth.js
  server/docs/authors-haven-api.yml
  server/helpers/createSocialUsers.js
  server/helpers/facebook.js
  server/helpers/getSocialUserData.js
  server/helpers/index.js
  server/helpers/passport.js
  server/middlewares/passportCallback.js
  server/middlewares/passportError.js
  server/routes/auth.js
  server/routes/index.js
  test/auth/__mocks_/index.js
  test/auth/facebookLogin.test.js
  test/auth/index.js
  test/helpers/index.js
  test/helpers/passportCallback.test.js
  test/index.test.js
Labels: pr:ready, type:feature

#23 #bg Remove Pre-commit Hook to Run Test
  package.json
Labels: pr:review

#22 #167190530 Implement User Sign Out
  server/controllers/Sessions.js
  server/docs/authors-haven-api.yml
  server/helpers/findToken.js
  server/routes/session.js
  test/helpers/findToken.test.js
  test/users/sessions.test.js
Labels: pr:ready, type:feature

#26 Refactor Database Models
  server/controllers/Users.js
  server/database/config/config.js
  server/database/models/user.js
  server/helpers/checkExistingUser.js
  server/helpers/index.js
  server/middlewares/verifyToken.js
  test/index.test.js
  test/middlewares/verifyToken.test.js
  test/models/index.js
  test/models/user.test.js
Labels: pr:review

#24 #167711183 Create user session during sign up
  server/controllers/Users.js
  test/users/signup.test.js
Labels: pr:review, type:fix

#25 #167574995 Enable Social Login via Google
  package-lock.json
  package.json
  server/controllers/Auth.js
  server/docs/authors-haven-api.yml
  server/helpers/getSocialUserData.js
  server/helpers/google.js
  server/helpers/passport.js
  server/routes/auth.js
  test/auth/__mocks_/index.js
  test/auth/facebook.test.js
  test/auth/google.test.js
  test/auth/index.js
Labels: pr:ready, type:feature

#31 Fix Generate Token Error
  server/controllers/Users.js
  server/helpers/generateToken.js
  test/middlewares/verifyToken.test.js
Labels: pr:ready, type:bug

#30 #167709071 Refactor Session Verification
  server/database/migrations/20190731135151-create-session.js
  server/database/models/session.js
  server/database/models/user.js
  server/database/seeds/20190731140725-demo-session.js
  server/helpers/findToken.js
  server/middlewares/verifyToken.js
  test/helpers/findToken.test.js
  test/models/__mocks__/index.js
  test/models/index.js
  test/models/sessions.test.js
Labels: pr:ready, type:chore

#28 #167575175 Setup Social Authentication via Twitter
  .env.sample
  package-lock.json
  package.json
  server/docs/authors-haven-api.yml
  server/helpers/getSocialUserData.js
  server/helpers/passport.js
  server/helpers/twitter.js
  server/index.js
  server/routes/auth.js
  test/auth/__mocks_/index.js
  test/auth/index.js
  test/auth/twitter.test.js
Labels: pr:ready, type:feature

#27 #167190540 Implement Follow And Unfollow User Feature
  server/controllers/Followers.js
  server/database/migrations/20190805160738-create-user-follower.js
  server/database/models/user.js
  server/database/models/userfollower.js
  server/docs/authors-haven-api.yml
  server/routes/follower.js
  server/routes/index.js
  server/routes/userFollower.js
  test/followers/follower.test.js
  test/followers/index.js
  test/index.test.js
  test/models/index.js
  test/models/userFollowers.test.js
Labels: pr:ready, type:feature

#29 #167190528 Build Email Verification Service
  .env.sample
  package-lock.json
  package.json
  server/controllers/Sessions.js
  server/controllers/Users.js
  server/database/migrations/20190730111558-create-user.js
  server/database/models/user.js
  server/docs/authors-haven-api.yml
  server/helpers/emailModule.js
  server/helpers/emailTemplates.js
  server/helpers/generateToken.js
  server/helpers/index.js
  server/middlewares/index.js
  server/middlewares/verifyToken.js
  server/routes/follower.js
  server/routes/user.js
  server/routes/userFollower.js
  test/helpers/emailModule.test.js
  test/helpers/index.js
  test/middlewares/verifyToken.test.js
  test/users/emailVerify.test.js
  test/users/index.js
  test/users/sessions.test.js
  test/users/signup.test.js
Labels: pr:review, type:feature

#36 #167782593 User Can Request Verification Email
  server/controllers/Sessions.js
  server/controllers/Users.js
  server/helpers/emailTemplates.js
  server/routes/user.js
  test/users/index.js
  test/users/resendVerifyEmail.js
Labels: pr:ready, type:feature

#35 #167706805 Enables an Already Logged In User To Change Their Password
  server/controllers/Users.js
  server/docs/authors-haven-api.yml
  server/middlewares/index.js
  server/middlewares/passwordValidation.js
  server/routes/user.js
  server/schemas/passwordChange.js
  test/middlewares/userValidation.test.js
  test/users/__mocks__/passwordReset.js
  test/users/index.js
  test/users/passwordChange.test.js
Labels: pr:ready, type:feature

#32 #167190533 Build User Profile
  server/controllers/Followers.js
  server/controllers/Users.js
  server/database/config/config.js
  server/database/migrations/20190730111558-create-user.js
  server/database/migrations/20190731135155-create-category.js
  server/database/migrations/20190731135158-create-hobby.js
  server/database/migrations/20190731135160-create-user-category.js
  server/database/migrations/20190731135165-create-user-hobby.js
  server/database/models/category.js
  server/database/models/hobby.js
  server/database/models/user.js
  server/database/seeds/20190730180408-my-seed-file.js
  server/database/seeds/20190731140728-categories-list.js
  server/database/seeds/20190731140730-hobbies-list.js
  server/helpers/validationHelper.js
  server/middlewares/index.js
  server/middlewares/profileValidation.js
  server/middlewares/userValidation.js
  server/schemas/index.js
  server/schemas/profileEdit.js
  test/followers/follower.test.js
  test/helpers/findToken.test.js
  test/middlewares/index.js
  test/middlewares/profileValidation.test.js
  test/models/category.test.js
  test/models/hobby.test.js
  test/models/index.js
  test/models/user.test.js
  test/models/userFollowers.test.js
  test/users/__mocks__/index.js
  test/users/emailVerify.test.js
  test/users/sessions.test.js
  test/users/signup.test.js
Labels: pr:review, type:feature

#39 Add Active Session Finder Middleware to Protected Routes
  server/controllers/Sessions.js
  server/middlewares/checkUserVerification.js
  server/middlewares/index.js
  server/routes/follower.js
  server/routes/userFollower.js
  test/middlewares/checkUserVerification.test.js
  test/middlewares/index.js
  test/users/sessions.test.js
Labels: pr:review, priority:high, type:bug

#33 #167706301 Edit User Profile
  .env.sample
  package-lock.json
  package.json
  server/controllers/Profiles.js
  server/database/config/cloudConfig.js
  server/database/seeds/20190730180408-my-seed-file.js
  server/docs/authors-haven-api.yml
  server/helpers/imageUpload.js
  server/helpers/index.js
  server/middlewares/index.js
  server/middlewares/multer.js
  server/routes/index.js
  server/routes/profile.js
  test/helpers/imageUpload.test.js
  test/helpers/index.js
  test/index.test.js
  test/profiles/__mocks__/image/test.png
  test/profiles/__mocks__/newUser.js
  test/profiles/index.js
  test/profiles/update.test.js
Labels: pr:ready, type:feature

#38 #167807720 Fix Enables Social User to be verified by default
  server/helpers/createSocialUsers.js
  test/auth/__mocks_/index.js
  test/auth/index.js
  test/auth/verifySocialUser.test.js
Labels: pr:review, type:fix

#34 #167190531 Implement User Reset Password Via Email
  server/controllers/Users.js
  server/database/migrations/20190807120440-create-reset-password-token.js
  server/database/models/resetpasswordtoken.js
  server/database/models/session.js
  server/database/models/user.js
  server/docs/authors-haven-api.yml
  server/helpers/emailTemplates.js
  server/helpers/index.js
  server/helpers/verifyResetPasswordToken.js
  server/middlewares/index.js
  server/middlewares/resetPasswordValidation.js
  server/routes/user.js
  server/schemas/resetPassword.js
  test/models/index.js
  test/models/resetPasswordToken.test.js
  test/users/index.js
  test/users/passwordReset.test.js
Labels: pr:review, type:feature

#40 Switch Test Database to PostgreSQL
  .env.sample
  .travis.yml
  server/database/config/config.js
Labels: pr:ready, priority:high

#37 #167783727 View User Profile
  server/controllers/Profiles.js
  server/controllers/Sessions.js
  server/controllers/Users.js
  server/docs/authors-haven-api.yml
  server/helpers/index.js
  server/helpers/userResponse.js
  server/routes/profile.js
  test/profiles/index.js
  test/profiles/view.test.js
Labels: pr:ready, type:feature

#44 #167190534 Implement User Create Article
  package-lock.json
  package.json
  server/controllers/Article.js
  server/database/migrations/20190813135136-create-article.js
  server/database/models/article.js
  server/database/models/user.js
  server/docs/authors-haven-api.yml
  server/helpers/validationHelper.js
  server/middlewares/articleValidation.js
  server/middlewares/index.js
  server/routes/article.js
  server/routes/index.js
  server/schemas/article.js
  server/schemas/index.js
  test/articles/__mocks__/index.js
  test/articles/create.test.js
  test/articles/index.js
  test/index.test.js
  test/models/article.test.js
  test/models/index.js
Labels: pr:ready, type:feature

#45 #167190554 Role Based Access Control Functionality
  server/database/migrations/20190730111558-create-user.js
  server/database/models/user.js
  server/database/seeds/20190730180408-my-seed-file.js
  server/middlewares/authorizeUser.js
  server/middlewares/index.js
  server/schemas/profileEdit.js
  test/middlewares/authorizeUser.test.js
  test/middlewares/index.js
  test/models/user.test.js
Labels: pr:ready, type:feature

#41 #167190542 Implement Article Tagging
  server/controllers/Article.js
  server/controllers/Articles.js
  server/controllers/Tags.js
  server/database/migrations/20190812113130-create-tag.js
  server/database/migrations/20190813161118-create-article-tag.js
  server/database/models/article.js
  server/database/models/tag.js
  server/database/seeds/20190730180408-my-seed-file.js
  server/database/seeds/20190812113159-demo-tag.js
  server/docs/authors-haven-api.yml
  server/helpers/index.js
  server/helpers/tagHelpers.js
  server/routes/article.js
  server/routes/index.js
  server/routes/tag.js
  server/schemas/article.js
  test/articles/__mocks__/index.js
  test/articles/create.test.js
  test/helpers/index.js
  test/helpers/tagHelper.test.js
  test/index.test.js
  test/models/index.js
  test/models/tag.test.js
  test/tags/associateArticle.test.js
  test/tags/createTag.test.js
  test/tags/getTag.test.js
  test/tags/index.js
Labels: pr:ready, type:feature

#43 #167190543 Build Pagination Support for Queries
  server/helpers/index.js
  server/helpers/paginationHelper.js
  server/helpers/validationHelper.js
  server/middlewares/index.js
  server/middlewares/paginationValidation.js
  server/schemas/index.js
  server/schemas/pagination.js
  test/helpers/index.js
  test/helpers/paginationHelper.test.js
  test/middlewares/index.js
  test/middlewares/paginationValidation.test.js
Labels: pr:ready, type:feature

#46 #167190538 Authenticated User Can Comment on an Existing Article
  server/controllers/Comments.js
  server/database/migrations/20190813135140-create-comment.js
  server/database/models/article.js
  server/database/models/comment.js
  server/database/models/user.js
  server/docs/authors-haven-api.yml
  server/helpers/index.js
  server/helpers/isFollowing.js
  server/middlewares/commentValidation.js
  server/middlewares/index.js
  server/routes/comment.js
  server/routes/index.js
  server/schemas/comment.js
  server/schemas/index.js
  test/articles/__mocks__/index.js
  test/comments/comment.test.js
  test/comments/index.js
  test/index.test.js
  test/middlewares/commentValidation.test.js
  test/middlewares/index.js
  test/models/comment.test.js
  test/models/index.js
  test/users/__mocks__/index.js
Labels: pr:ready, type:feature

#47 #167918277 Implement Create Category Functionality
  server/controllers/Categories.js
  server/database/migrations/20190731135155-create-category.js
  server/database/models/category.js
  server/database/seeds/20190730180408-my-seed-file.js
  server/docs/authors-haven-api.yml
  server/middlewares/createCategoryValidation.js
  server/middlewares/index.js
  server/routes/category.js
  server/routes/index.js
  server/schemas/category.js
  server/schemas/index.js
  test/categories/createCategory.test.js
  test/categories/index.js
  test/index.test.js
  test/middlewares/createCategoryValidation.test.js
  test/middlewares/index.js
  test/users/__mocks__/index.js
Labels: pr:review, type:feature

#48 #167190539 Implement Like and Dislike Functionality
  server/controllers/Articles.js
  server/database/migrations/20190813135140-create-like.js
  server/database/migrations/20190813135145-create-dislike.js
  server/database/models/article.js
  server/database/models/dislike.js
  server/database/models/like.js
  server/database/models/user.js
  server/database/seeds/20190731140735-articles-seeds.js
  server/docs/authors-haven-api.yml
  server/routes/article.js
  test/articles/__mocks__/index.js
  test/articles/index.js
  test/articles/likeOrDislikeArticle.test.js
  test/articles/removeArticleLikeOrDislike.test.js
  test/index.test.js
Labels: pr:ready, type:feature

#54 #167974866 Fix User Response Data
  server/controllers/Profiles.js
  test/profiles/view.test.js
Labels: pr:review, type:fix

#52 #167917588 Authenticated User can Update and Delete Comments
  server/controllers/Comments.js
  server/docs/authors-haven-api.yml
  server/routes/comment.js
  server/routes/index.js
  test/articles/__mocks__/index.js
  test/comments/comment.test.js
  test/comments/index.js
  test/comments/updateComment.test.js
Labels: pr:review, type:feature

#55 #167969545 Add Category On Article Creation
  server/controllers/Articles.js
  server/database/migrations/20190813135136-create-article.js
  server/database/models/article.js
  server/database/models/category.js
  server/database/seeds/20190731140728-categories-list.js
  server/docs/authors-haven-api.yml
  server/schemas/article.js
  test/articles/__mocks__/index.js
  test/articles/create.test.js
Labels: pr:review, type:feature

#51 #167899328 Setup Article Update
  server/controllers/Articles.js
  server/docs/authors-haven-api.yml
  server/helpers/categoryHandler.js
  server/middlewares/articleEditValidation.js
  server/middlewares/index.js
  server/routes/article.js
  server/schemas/articleEdit.js
  server/schemas/index.js
  test/articles/__mocks__/index.js
  test/articles/index.js
  test/articles/update.test.js
Labels: pr:review, type:feature

#50 #167190545 Add Search Functionality
  server/controllers/Search.js
  server/docs/authors-haven-api.yml
  server/helpers/index.js
  server/helpers/paginationHelper.js
  server/helpers/searchCategorizer.js
  server/middlewares/index.js
  server/middlewares/searchValidation.js
  server/routes/index.js
  server/routes/search.js
  server/schemas/index.js
  server/schemas/search.js
  test/helpers/paginationHelper.test.js
  test/index.test.js
  test/search/index.js
  test/search/search.test.js
Labels: pr:ready, type:feature

#57 Fix Tag Limit And Spacing
  server/controllers/Articles.js
  server/controllers/Tags.js
  server/helpers/tagHelpers.js
  test/articles/__mocks__/index.js
  test/articles/create.test.js
Labels: pr:review, type:fix
