Repository andela/ah-rambo-backend, pull requests merged in 2019-09, with the labels that each got.

#59 #168257202 Add Cors Functionality
  package-lock.json
  package.json
  server/index.js
Labels: pr:ready, type:chore

#58 #168252582 Gets All Users Articles
  server/controllers/Articles.js
  server/database/models/article.js
  server/docs/authors-haven-api.yml
  server/routes/article.js
  test/articles/getUserArticles.test.js
  test/articles/index.js
Labels: pr:ready, type:feature

#60 Add Social Login Redirect URLs
  server/controllers/Auth.js
  server/controllers/Profiles.js
  server/routes/auth.js
  server/routes/profile.js
  test/auth/facebook.test.js
  test/auth/google.test.js
  test/auth/twitter.test.js
  test/profiles/view.test.js
Labels: pr:ready, priority:high, type:bug

#53 #167940543 Implement Global Search
  server/controllers/Search.js
  server/database/migrations/create-search.js
  server/database/models/article.js
  server/database/models/category.js
  server/database/models/index.js
  server/database/models/tag.js
  server/database/models/user.js
  server/helpers/searchCategorizer.js
  server/schemas/search.js
  test/articles/__mocks__/index.js
  test/search/search.test.js
Labels: pr:review, type:feature
