Repository andela/ah-rambo-backend, pull requests merged in 2019-07, with the labels that each got.

#4 #167190520 Configure ESLint
  .eslintignore
  .eslintrc.json
  package-lock.json
  package.json
Labels: peer review

#3 #167190521 Integrate HoundCI with Badge Attached to Readme
  .hound.yml
  README.md
Labels: TTL review

#2 #167436402 Setup Server
  .babelrc
  .gitignore
  package-lock.json
  package.json
  server/index.js
Labels: TTL review

#5 #167190522 Deploy App to Heroku
  .eslintrc.json
  app.json
Labels: TTL review

#6 #167190523 Setup Unit Test
  .babelrc
  .editorconfig
  .env.sample
  .eslintrc.json
  .hound.yml
  __test__/index.test.js
  package-lock.json
  package.json
  server/app.js
  server/index.js
Labels: pr:ready, type:chore

#8 #167190524 Integrate Coveralls
  .coveralls.yml
  README.md
  package-lock.json
  package.json
Labels: pr:ready, type:chore

#7 #167190518 Integrate TravisCI
  .travis.yml
  README.md
Labels: pr:ready, type:chore

#10 #167515607 Change Unit Testing to Use Mocha and Chai
  .eslintrc.json
  .gitignore
  __test__/index.test.js
  package-lock.json
  package.json
  server/app.js
  server/index.js
  test/index.test.js
Labels: pr:review, type:chore, type:ci

#11 #167190525 Setup API Documentation Using Swagger
  package-lock.json
  package.json
  server/docs/authors-haven-api.yml
  server/index.js
Labels: pr:review, type:chore, type:docs

#9 #167190519 Setup Database With Sequelize ORM
  .env.sample
  .sequelizerc
  package-lock.json
  package.json
  server/database/config/config.js
  server/database/models/index.js
  server/index.js
Labels: pr:review, type:chore

#12 #167507938 Setup Pre-commit Hooks with Husky
  .lintstagedrc
  package-lock.json
  package.json
  server/database/config/config.js
  server/database/models/index.js
Labels: pr:ready, type:chore

#16 #167618839 Fix Bugs in Database Config Path
  .hound.yml
  .sequelizerc
  package.json
  server/database/config/config.js
  server/database/models/index.js
Labels: pr:ready, priority:high, type:bug
